import { ArrowLeft, ArrowUpRight, Check, GraduationCap, Languages, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { Link, useParams } from "wouter";
import { trpc } from "@/lib/trpc";
import { RecordCard, SectionHeading, StatusBadge } from "@/components/ArchivePrimitives";

export default function PractitionerProfile() {
  const { id = "" } = useParams<{ id: string }>();
  const { data, isLoading, isError } = trpc.archive.practitioner.useQuery({ id });
  if (isLoading) return <div className="mx-auto max-w-5xl px-5 py-24"><div className="h-48 animate-pulse rounded-[1.5rem] bg-muted" /></div>;
  if (isError || !data) return <div className="mx-auto max-w-3xl px-5 py-24 text-center"><p className="font-mono-archive text-[10px] uppercase tracking-[0.16em] text-accent">Profile unavailable</p><h1 className="mt-3 font-display text-5xl text-primary">This public profile is not available.</h1><Link href="/masters" className="mt-7 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-white">Return to Find a Master <ArrowUpRight className="size-4" /></Link></div>;
  const { person, approvedRecords } = data;

  return <div className="mx-auto max-w-[1440px] px-5 pb-20 pt-14 sm:px-8 lg:px-12 lg:pt-20"><Link href="/masters" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-muted-foreground hover:text-accent"><ArrowLeft className="size-3.5" /> Find a master</Link><section className="mt-8 grid gap-8 rounded-[1.5rem] bg-primary p-7 text-primary-foreground sm:p-10 lg:grid-cols-[.35fr_1fr_.8fr] lg:items-end"><div className="grid size-28 place-items-center rounded-full bg-[#efe5d5] font-display text-6xl text-primary sm:size-36 sm:text-7xl">{person.displayName.charAt(0)}</div><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono-archive text-[10px] uppercase tracking-[0.18em] text-[#e6ba63]">Consented public profile</p><StatusBadge status={person.verificationStatus} /></div><h1 className="mt-3 font-display text-6xl leading-[.9] tracking-[-.04em] text-white sm:text-8xl">{person.displayName}</h1><p className="mt-4 text-lg text-white/70">{person.role}</p></div><div className="space-y-3 text-sm text-white/75 lg:justify-self-end"><p className="flex items-center gap-2"><MapPin className="size-4 text-[#e6ba63]" /> {person.district}, {person.region}</p><p className="flex items-center gap-2"><Languages className="size-4 text-[#e6ba63]" /> {person.languages.join(" · ")}</p>{person.workshopAvailable && <p className="flex items-center gap-2"><GraduationCap className="size-4 text-[#e6ba63]" /> Workshops available by consent</p>}</div></section>
    <section className="mt-10 grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeading kicker="About the knowledge holder" title="A person before a profile." description="This page shares only what has been agreed for public discovery. It does not expose private contact details or guarantee availability." /><p className="mt-6 text-base leading-8 text-muted-foreground">{person.biography}</p><div className="mt-7 flex flex-wrap gap-2">{person.specialties.map((specialty) => <span key={specialty} className="rounded-full bg-secondary px-3 py-1.5 text-xs font-semibold text-primary">{specialty}</span>)}</div><div className="mt-8 flex items-start gap-3 rounded-2xl border border-accent/20 bg-[#fffaf1] p-4 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-accent" /><span><strong className="text-primary">Public listing is consented.</strong> Archive links below are restricted to records that are already approved for public discovery.</span></div></div><div><div className="mb-5 flex items-end justify-between gap-4"><div><p className="font-mono-archive text-[10px] uppercase tracking-[0.16em] text-accent">Approved archive links</p><h2 className="mt-2 font-display text-4xl text-primary">Knowledge in context.</h2></div><span className="text-xs text-muted-foreground">{approvedRecords.length} public records</span></div>{approvedRecords.length ? <div className="grid gap-5 sm:grid-cols-2">{approvedRecords.map((record) => <RecordCard key={record.id} record={record} />)}</div> : <div className="rounded-2xl border border-dashed border-border bg-card p-8 text-center"><UserRound className="mx-auto size-7 text-accent" /><p className="mt-3 font-display text-2xl text-primary">No approved archive links yet.</p><p className="mt-2 text-sm text-muted-foreground">The profile can exist before a record becomes public.</p></div>}</div></section><section className="mt-16 flex flex-col justify-between gap-5 rounded-[1.5rem] border border-border bg-card p-7 sm:flex-row sm:items-center sm:p-9"><div><p className="font-mono-archive text-[10px] uppercase tracking-[0.17em] text-accent">Keep the relationship visible</p><h2 className="mt-2 font-display text-4xl leading-none text-primary">Read the record, not just the name.</h2></div><Link href="/document" className="inline-flex items-center justify-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-white">Document with consent <ArrowUpRight className="size-4" /></Link></section>
  </div>;
}
