import { useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft, ArrowUpRight, Check, Clock3, ExternalLink, FileText, Info, MapPin, Network, Quote, ShieldCheck, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { AudioEvidencePlayer, EvidenceRow, KnowledgeCard, MediaPill, RiskBadge, StatusBadge } from "@/components/ArchivePrimitives";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export default function RecordDetail() {
  const [, params] = useRoute("/record/:slug");
  const slug = params?.slug ?? "";
  const { data, isLoading, isError } = trpc.archive.get.useQuery({ slug }, { enabled: Boolean(slug) });
  const [activeTimecode, setActiveTimecode] = useState<string>();
  const record = data?.record;

  if (isLoading) return <div className="mx-auto max-w-[1440px] px-5 py-24 sm:px-8 lg:px-12"><div className="h-10 w-32 animate-pulse rounded bg-muted" /><div className="mt-8 h-24 max-w-3xl animate-pulse rounded bg-muted" /></div>;
  if (isError || !record) return <div className="mx-auto max-w-2xl px-5 py-24 text-center"><p className="font-mono-archive text-[10px] uppercase tracking-[0.2em] text-accent">Record unavailable</p><h1 className="mt-4 font-display text-5xl text-primary">This story is not public yet.</h1><p className="mt-4 text-sm leading-6 text-muted-foreground">Some archive material stays private or in review until consent and verification are complete.</p><Link href="/explore" className="mt-7 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-white">Return to explore <ArrowUpRight className="size-4" /></Link></div>;
  const riskScore = record.risk.score ?? 0;
  const isOrientation = Boolean(record.referenceUrl);

  return <div className="pb-20">
    <section className="border-b border-border bg-[#efe5d5]"><div className="mx-auto max-w-[1440px] px-5 pb-14 pt-9 sm:px-8 lg:px-12 lg:pb-20 lg:pt-12"><Link href="/explore" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-muted-foreground hover:text-accent"><ArrowLeft className="size-3.5" /> Back to archive</Link><div className="mt-12 grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><p className="font-mono-archive text-[10px] uppercase tracking-[0.2em] text-accent">{record.eyebrow}</p>{isOrientation && <span className="rounded-full bg-secondary px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.1em] text-primary">National orientation card</span>}<StatusBadge status={record.status} /><RiskBadge level={record.risk.level} score={record.risk.score} /></div><h1 className="mt-5 max-w-4xl font-display text-6xl leading-[.86] tracking-[-.05em] text-primary sm:text-8xl">{record.title}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted-foreground">{record.shortDescription}</p></div><div className="lg:justify-self-end"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-primary font-display text-2xl text-primary-foreground">{record.practitionerName.charAt(0)}</span><div><p className="font-bold text-primary">{record.practitionerName}</p><p className="text-xs text-muted-foreground">{isOrientation ? "Documentation status" : "Knowledge holder"} · {record.district}, {record.region}</p></div></div><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="size-3.5 text-accent" /> Public-safe location · {record.village}</div></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 pt-8 sm:px-8 lg:px-12"><div className="flex flex-wrap gap-2"><MediaPill type="video" label={isOrientation ? "Primary media pending consent" : `${record.media.length} source assets`} /><MediaPill type="audio" label={isOrientation ? "Language to be documented" : `Original ${record.originalLanguage}`} /><MediaPill type="photo" label={isOrientation ? "Context pending source" : "Process context"} /><span className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 text-xs text-muted-foreground"><ShieldCheck className="size-3.5 text-accent" /> {record.sourceLabel}</span>{record.referenceUrl && <a href={record.referenceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 text-xs font-semibold text-accent hover:bg-secondary"><ExternalLink className="size-3.5" /> Reference inventory</a>}</div></section>

    <section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-10 sm:px-8 lg:grid-cols-[.72fr_1.28fr] lg:px-12 lg:py-14"><aside className="space-y-5 lg:sticky lg:top-28 lg:self-start"><AudioEvidencePlayer record={record} activeTimecode={activeTimecode} /><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Quote className="size-4 text-accent" /><p className="font-mono-archive text-[10px] uppercase tracking-[0.16em] text-accent">{isOrientation ? "Primary source status" : "Original testimony"}</p></div><p className="mt-4 text-lg leading-8 text-primary">“{record.transcript.original}”</p><div className="mt-4 border-t border-border pt-4"><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground">{isOrientation ? "Documentation requirement" : `Translation · ${record.transcript.language} → English`}</p><p className="mt-2 text-sm leading-6 text-foreground/75">{record.transcript.translation}</p></div><div className={cn("mt-5 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.1em]", isOrientation ? "text-[#8a6212]" : "text-[#5a8c74]")}><Check className="size-3.5" /> {isOrientation ? "Source required before primary publication" : "Source transcript retained"}</div></div><div className="rounded-2xl border border-accent/20 bg-[#fffaf1] p-5"><div className="flex gap-3"><Info className="mt-0.5 size-4 shrink-0 text-accent" /><p className="text-xs leading-5 text-muted-foreground">AI-assisted fields are annotations on the source. The archive keeps uncertainty and review status visible so visitors can judge the record with care.</p></div></div></aside>
      <div><div className="mb-8 flex items-end justify-between gap-4"><div><p className="font-mono-archive text-[10px] uppercase tracking-[0.18em] text-accent">Structured knowledge</p><h2 className="mt-2 font-display text-4xl text-primary sm:text-5xl">What the recording holds.</h2></div><span className="hidden items-center gap-2 text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground sm:flex"><Sparkles className="size-3.5 text-accent" /> AI-assisted · evidence-linked</span></div><div className="grid gap-4">{record.knowledge.map((block) => <KnowledgeCard key={block.kind} block={block} onPlay={(timecode) => setActiveTimecode(timecode)} />)}</div></div></section>

    <section className="border-y border-border bg-card"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12 lg:py-16"><div><p className="font-mono-archive text-[10px] uppercase tracking-[0.18em] text-accent">Relationships</p><h2 className="mt-3 font-display text-4xl leading-none text-primary">The record has a place in a larger story.</h2><p className="mt-4 max-w-md text-sm leading-6 text-muted-foreground">Lightweight links keep materials, tools, festivals, people, and places connected without pretending a graph can replace lived context.</p></div><div className="grid gap-3 sm:grid-cols-2">{record.relationships.map((relationship) => <div key={`${relationship.type}-${relationship.label}`} className="flex items-center gap-3 rounded-xl border border-border bg-background p-4"><span className="grid size-9 place-items-center rounded-full bg-secondary text-accent"><Network className="size-4" /></span><div><p className="font-mono-archive text-[9px] uppercase tracking-[0.12em] text-muted-foreground">{relationship.type}</p><p className="mt-0.5 font-semibold text-primary">{relationship.label}</p><p className="text-xs text-muted-foreground">{relationship.detail}</p></div></div>)}</div></div></section>

    <section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1fr_1fr] lg:px-12 lg:py-20"><div><div className="flex items-center gap-2"><p className="font-mono-archive text-[10px] uppercase tracking-[0.18em] text-accent">Risk indicator</p><RiskBadge level={record.risk.level} score={record.risk.score} /></div><h2 className="mt-3 font-display text-4xl leading-none text-primary">Prioritise documentation,<br />not cultural value.</h2><p className="mt-5 max-w-md text-sm leading-6 text-muted-foreground">This transparent indicator helps an archive identify where documentation may be urgent. It is not a measure of a tradition’s importance, and it cannot replace community judgment.</p><div className="mt-8 flex items-center gap-4"><div className="relative grid size-28 place-items-center rounded-full" style={{ background: isOrientation ? "#eadfce" : `conic-gradient(#c7663d ${riskScore}%, #eadfce 0)` }}><div className="grid size-20 place-items-center rounded-full bg-background"><span className="font-display text-3xl text-primary">{isOrientation ? "—" : riskScore}</span></div></div><div><p className="font-semibold text-primary">{isOrientation ? "Assessment pending" : record.risk.level === "high" ? "High priority" : "Active continuity"}</p><p className="mt-1 text-xs text-muted-foreground">{isOrientation ? "A score needs consented evidence and documented factors" : "Ruleset v1 · illustrative demo assessment"}</p></div></div></div><div className="rounded-2xl border border-border bg-background p-6"><div className="mb-5 flex items-center justify-between"><p className="font-mono-archive text-[10px] uppercase tracking-[0.16em] text-accent">Factor breakdown</p><span className="text-[10px] text-muted-foreground">{record.risk.factors.length} factor{record.risk.factors.length === 1 ? "" : "s"}</span></div><div className="grid gap-4">{record.risk.factors.map((factor) => <div key={factor.label} className="flex items-start justify-between gap-4 border-b border-border pb-3 last:border-b-0 last:pb-0"><div><p className="text-sm font-semibold text-primary">{factor.label}</p><p className="mt-0.5 text-xs text-muted-foreground">{factor.note}</p></div><span className="shrink-0 rounded-full bg-secondary px-2.5 py-1 font-mono-archive text-[10px] text-primary">{factor.value}</span></div>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 pb-4 sm:px-8 lg:px-12"><div className="rounded-2xl border border-border bg-card p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#e6f3e9] text-[#2f654d]"><ShieldCheck className="size-5" /></div><div><p className="font-display text-2xl text-primary">Verification history</p><p className="text-xs text-muted-foreground">Who has reviewed this record, and what changed.</p></div></div><Link href="/verify" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-accent">Review a record <ExternalLink className="size-3.5" /></Link></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-background p-4"><p className="font-mono-archive text-[9px] uppercase tracking-[0.12em] text-muted-foreground">01 · Source</p><p className="mt-2 text-sm font-semibold text-primary">Original testimony attached</p><p className="mt-1 text-xs text-muted-foreground">{record.sourceLabel}</p></div><div className={cn("rounded-xl p-4", record.status === "expert" ? "bg-[#eaf0fb]" : "bg-[#e6f3e9]")}><p className="font-mono-archive text-[9px] uppercase tracking-[0.12em] text-muted-foreground">02 · Review</p><p className="mt-2 text-sm font-semibold text-primary">{record.status === "expert" ? "Expert verification" : "Community verification"}</p><p className="mt-1 text-xs text-muted-foreground">Evidence and context checked</p></div><div className="rounded-xl bg-background p-4"><p className="font-mono-archive text-[9px] uppercase tracking-[0.12em] text-muted-foreground">03 · Publication</p><p className="mt-2 text-sm font-semibold text-primary">Public discovery enabled</p><p className="mt-1 text-xs text-muted-foreground">Consent state: approved for public pilot</p></div></div>{data?.verification?.length ? <div className="mt-5 space-y-2">{data.verification.map((event) => <div key={event.id} className="text-xs text-muted-foreground">{event.decision} · {event.comment}</div>)}</div> : null}</div></section>

    <section className="mx-auto max-w-[1440px] px-5 pt-10 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-5 rounded-2xl bg-primary p-6 text-primary-foreground sm:flex-row sm:items-center sm:p-8"><div><p className="font-mono-archive text-[10px] uppercase tracking-[0.16em] text-[#e6ba63]">Continue exploring</p><h2 className="mt-2 font-display text-3xl text-white">Find another voice from India.</h2></div><div className="flex flex-wrap gap-3"><Link href="/explore" className="inline-flex items-center gap-2 rounded-full bg-accent px-4 py-2.5 text-xs font-bold text-accent-foreground">Explore archive <ArrowUpRight className="size-3.5" /></Link><Link href="/map" className="inline-flex items-center gap-2 rounded-full border border-primary-foreground/20 px-4 py-2.5 text-xs font-bold text-white">Open map <MapPin className="size-3.5" /></Link></div></div></section>
  </div>;
}
